local h = require('helpers')
local inkmd = require('inkmd')

describe('toggle', function()
  it('clears marks and restores window options, then renders again', function()
    vim.wo.conceallevel = 1
    local buf = h.open('basic.md', { 21, 0 })
    h.eq(vim.wo.conceallevel, 3)
    vim.cmd('Inkmd')
    h.eq(#h.marks(buf), 0)
    h.eq(vim.wo.conceallevel, 1)
    h.eq(h.screen()[1], '# Heading one')
    vim.cmd('Inkmd')
    h.eq(vim.wo.conceallevel, 3)
    h.eq(h.screen()[1], '󰲡 Heading one')
  end)

  it('stays disabled across edits', function()
    local buf = h.open('basic.md', { 21, 0 })
    inkmd.disable(buf)
    vim.api.nvim_buf_set_lines(buf, 0, 1, false, { '# Changed' })
    inkmd.render_now(buf)
    h.eq(#h.marks(buf), 0)
  end)

  it('applies to every buffer with a bang', function()
    local a = h.open('basic.md', { 21, 0 })
    local b = h.scratch({ '# Other' }, { 1, 0 })
    vim.cmd('Inkmd! disable')
    h.eq(inkmd.is_enabled(a), false)
    h.eq(inkmd.is_enabled(b), false)
    vim.cmd('Inkmd! enable')
    h.eq(inkmd.is_enabled(a), true)
    h.eq(inkmd.is_enabled(b), true)
  end)

  it('gives a window back its options when it shows another buffer', function()
    vim.wo.conceallevel = 0
    h.open('basic.md', { 21, 0 })
    h.eq(vim.wo.conceallevel, 3)
    vim.cmd('enew')
    h.eq(vim.wo.conceallevel, 0)
  end)
end)
